import { 
  Shield, Wifi, Car, Trees, Waves, Dumbbell, Flower2, ArrowUpCircle, 
  UserCircle, Zap, Sun, Video, Flame, Droplets, Smile, Baby, 
  Briefcase, BatteryCharging, Navigation, Users, Dog, Trash, 
  Film, Camera, Coffee, Wind, Snowflake, Activity, Book, 
  Gamepad2, Music, MapPin, Key, Lock, ShieldCheck, Eye, 
  Plane, ShoppingBag, ShoppingCart, Train, Bus, Building, 
  Building2, Home, Utensils, Heart, Stethoscope, Plus, 
  Anchor, Palmtree, Tv, CheckCircle, Bell, PhoneCall
} from 'lucide-react';

export const AVAILABLE_ICONS = {
  'Shield': Shield,
  'Wifi': Wifi,
  'Car': Car,
  'Trees': Trees,
  'Waves': Waves,
  'Dumbbell': Dumbbell,
  'Flower2': Flower2,
  'ArrowUpCircle': ArrowUpCircle,
  'UserCircle': UserCircle,
  'Zap': Zap,
  'Sun': Sun,
  'Video': Video,
  'Flame': Flame,
  'Droplets': Droplets,
  'Smile': Smile,
  'Baby': Baby,
  'Briefcase': Briefcase,
  'BatteryCharging': BatteryCharging,
  'Navigation': Navigation,
  'Users': Users,
  'Dog': Dog,
  'Trash': Trash,
  'Film': Film,
  'Camera': Camera,
  'Coffee': Coffee,
  'Wind': Wind,
  'Snowflake': Snowflake,
  'Activity': Activity,
  'Book': Book,
  'Gamepad2': Gamepad2,
  'Music': Music,
  'MapPin': MapPin,
  'Key': Key,
  'Lock': Lock,
  'ShieldCheck': ShieldCheck,
  'Eye': Eye,
  'Plane': Plane,
  'ShoppingBag': ShoppingBag,
  'ShoppingCart': ShoppingCart,
  'Train': Train,
  'Bus': Bus,
  'Building': Building,
  'Building2': Building2,
  'Home': Home,
  'Utensils': Utensils,
  'Heart': Heart,
  'Stethoscope': Stethoscope,
  'Plus': Plus,
  'Anchor': Anchor,
  'Palmtree': Palmtree,
  'Tv': Tv,
  'CheckCircle': CheckCircle,
  'Bell': Bell,
  'PhoneCall': PhoneCall
};
